apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: employee-pvc
  namespace : {{.Values.namespace}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: "manual"
